config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en/ do
    devise_for :users, skip: :omniauth_callbacks
    
    root "pages#index"

    if Rails.application.config.enable_sign_in_as
      get 'login_as', to: "sessions#login_as"
    end

    namespace :backend do
      resources :users

      resources :leave_applications, except: [:show, :destroy] do
        get :verify, on: :member
        get :statistics, on: :collection
      end

      resources :leave_times, except: [:edit, :update, :destroy] do
        post :append_quota, on: :collection
        get :batch_new, on: :collection
        post :batch_create, on: :collection
      end

      resources :overtimes, except: [:show, :destroy] do
        get :verify, :add_leave_time, :add_compensatory_pay, on: :member
        post :create_leave_time, :create_compensatory_pay, on: :member
        get :statistics, on: :collection
      end

      resources :bonus_leave_time_logs, only: [:index, :update]
    end

    resources :leave_applications, except: [:destroy] do
      member do
        put "cancel"
      end

      collection do
        get "/:status", to: "leave_applications#index",
                        constraints: { status: /pending|approved|rejected|canceled/ }
      end
    end

    resources :leave_times, only: [:index, :show]
    resources :remote, only: [:new, :create, :update, :edit]

    resources :overtimes, except: :destroy do
      member do
        put "cancel"
      end
    end

  end
end

app/models/overtime.rb
# frozen_string_literal: true

class Overtime < ApplicationRecord
  include AASM
  include SignatureConcern

  enum status: Settings.overtimes.statuses
  enum compensatory_type: Settings.overtimes.compensatory_types

  belongs_to :user
  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id'

  has_one :overtime_pay

  validates :description, :start_time, :end_time, :compensatory_type, presence: true
  validate :hours_should_be_positive_integer
  validate :time_overlapped

  before_validation :assign_hours

  aasm column: :status, enum: true do
    state :pending, initial: true
    state :approved
    state :rejected
    state :canceled

    event :approve, before: proc { |manager| sign(manager) } do
      transitions to: :approved, from: :pending
    end

    event :reject, before: proc { |manager| sign(manager) } do
      transitions to: :rejected, from: %i(pending approved)
    end

    event :revise do
      transitions to: :pending, from: %i(pending)
    end

    event :cancel do
      transitions to: :canceled, from: %i(pending approved)
    end
  end

  def leave_time_params
    {
      user_id: self.user_id,
      leave_type: 'bonus',
      quota: self.hours,
      effective_date: self.start_time.to_date,
      expiration_date: self.start_time.to_date.end_of_year
    }
  end

  ransacker :year do
    Arel.sql('extract(year from created_at)')
  end

  ransacker :month do
    Arel.sql('extract(month from created_at)')
  end

  private

  def assign_hours
    return unless start_time && end_time

    self.hours = ((end_time - start_time) / 3600).to_i
  end

  def hours_should_be_positive_integer
    return if errors.any?

    errors.add(:end_time, :not_integer) unless ((end_time - start_time).to_i % 3600).zero?
    errors.add(:start_time, :should_be_earlier) unless end_time > start_time
  end

  def time_overlapped
    return if errors.any?

    overlapped_records = self.class.ransack(user_id_eq: user_id, id_not_eq: id).result
                                   .where('(start_time, end_time) OVERLAPS (?, ?)', start_time, end_time)

    return unless overlapped_records.any?

    time_overlapped_errors(overlapped_records)
  end

  def time_overlapped_errors(records)
    url = Rails.application.routes.url_helpers
    records.each do |record|
      next if record.rejected? || record.canceled?

      errors.add(
        :base,
        I18n.t(
          'activerecord.errors.models.overtime.attributes.base.time_range_overlapped',
          start_time: record.start_time.to_formatted_s(:month_date),
          end_time: record.end_time.to_formatted_s(:month_date),
          link: url.overtime_path(id: record.id)
        )
      )
    end
  end
end

app/controllers/backend/base_controller.rb
# frozen_string_literal: true

class Backend::BaseController < ::BaseController
  before_action :authenticate_hr!

  def authenticate_hr!
    redirect_to root_path unless current_user.is_hr? || current_user.is_manager?
  end

  def authenticate_manager!
    redirect_to root_path unless current_user.is_manager?
  end
end

app/controllers/backend/leave_applications_controller.rb
# frozen_string_literal: true

class Backend::LeaveApplicationsController < Backend::BaseController
  include Selectable
  before_action :set_query_object

  def index
    @users = User.where.not(role: 'resigned')
  end

  def create
    @current_object = collection_scope.new(resource_params)
    if @current_object.save
      @current_object.approve!(current_user)
      action_success
    else
      render action: :new
    end
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def statistics
    usernames = params.dig(:usernames).to_s.split(',')
    if usernames.empty?
      @users = User.filter_by_role(%w[employee parttime])
    else
      @users = User.where(login_name: usernames)
    end
    @summary = LeaveTimeSummaryService.new(
      specific_year.to_i,
      specific_month.to_i,
      @users
    ).summary
  end

  private

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def collection_scope
    if params[:id]
      LeaveApplication
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    case action_name
    when 'create' then params.require(:leave_application).permit(:user_id, :leave_type, :start_time, :end_time, :description, :comment)
    when 'update' then params.require(:leave_application).permit(:comment)
    end
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :leave_type_eq, :user_id_eq, :status_eq, :end_date_gteq, :start_date_lteq)
    @search_params.present? ? @search_params : @search_params.merge(status_eq: :pending)
  end

  def set_query_object
    @q = LeaveApplication.ransack(search_params)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index, controller: controller_path, params: { status: :pending })
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/leave_times_controller.rb
# frozen_string_literal: true

class Backend::LeaveTimesController < Backend::BaseController
  before_action :set_query_object

  def index
  end

  def new
    @current_object = LeaveTime.new
  end

  def create
    @current_object = LeaveTime.new(resource_params)
    return render action: :new unless @current_object.save

    if request.env['HTTP_REFERER'].include?('leave_application_id')
      verify_id = request.env['HTTP_REFERER'].partition('=').last
      action_success(verify_backend_leave_application_path(verify_id))
    else
      action_success
    end
  end

  def append_quota
    @current_object = collection_scope.new(leave_time_params_by_leave_application)
    render :new
  end

  def batch_new
    @current_object = LeaveTime.new
  end

  def batch_create
    user_ids = params[:leave_time][:user_id]
    user_ids.each do |user_id|
      @current_object = LeaveTime.new(batch_leave_time_params.merge(user_id: user_id))
      return render action: :batch_new unless @current_object.save
    end
    action_success
  end

  private

  def leave_time_params_by_leave_application
    leave_application = LeaveApplication.find(params[:leave_application_id])
    leave_application.leave_time_params
  end

  def set_query_object
    @q = LeaveTime.ransack(search_params)
  end

  def collection_scope
    if params[:id]
      LeaveTime.preload(:user, leave_time_usages: :leave_application)
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    params.require(:leave_time).permit(
      :user_id, :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def batch_leave_time_params
    params.require(:leave_time).permit(
      :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :leave_type_eq, :effective_true, :user_id_eq)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index)
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/overtimes_controller.rb
# frozen_string_literal: true

class Backend::OvertimesController < Backend::BaseController
  before_action :set_query_object, except: :statistics

  def index
    @users = User.all
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def add_leave_time
    @leave_time = LeaveTime.new
  end

  def create_leave_time
    params[:leave_time][:user_id] = current_object.user.id
    @leave_time = LeaveTime.new(resource_params)
    if @leave_time.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_leave_time
    end
  end

  def add_compensatory_pay
    @overtime_pay = OvertimePay.new
  end

  def create_compensatory_pay
    params[:overtime_pay][:user_id] = current_object.user.id
    params[:overtime_pay][:overtime_id] = params[:id]
    @overtime_pay = OvertimePay.new(resource_params)
    if @overtime_pay.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_overtime_pay
    end
  end

  def statistics
    search_params = params.fetch(:q, {})&.permit(:year_eq, :month_eq)
    @q = Overtime.where(compensatory_type: 'pay', status: :approved).ransack(search_params)
    @summary = @q.result
  end

  private

  def resource_params
    case action_name
    when 'create' then params.require(:overtime).permit(:user_id, :hours, :start_time, :end_time, :description)
    when 'update' then params.require(:overtime).permit(:comment)
    when 'create_leave_time' then params.require(:leave_time).permit(:user_id, :overtime_id, :leave_type, :quota, :effective_date, :expiration_date, :remark)
    when 'create_compensatory_pay' then params.require(:overtime_pay).permit(:user_id, :overtime_id, :hour, :remark)
    end
  end

  def set_query_object
    @q = Overtime.ransack(search_params)
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :status_eq, :end_time_lteq, :start_time_gteq, :compensatory_type_eq)
  end

  def collection_scope
    @q.result.preload(:user)
  end

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

class Backend::UsersController < Backend::BaseController
  before_action :set_query_object
  before_action :set_minimum_password_length, only: %i(new edit)

  def show
    @leave_times = current_object.leave_times
  end

  def update
    if password_blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    super
  end

  def new
    @current_object = User.new
  end

  def edit
  end

  private

  def set_query_object
    @q = User.ransack(search_params)
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :id_eq, :role_eq, :login_name_cont_any)
  end

  def collection_scope
    if params[:id]
      User
    else
      @q.result.order(id: :desc).page(params[:page])
    end
  end

  def resource_params
    params.require(:user).permit(
      :id, :name, :email, :login_name, :role,
      :password, :password_confirmation,
      :join_date, :leave_date,
      :assign_leave_time, :assign_date
    )
  end

  def set_minimum_password_length
    @minimum_password_length = 6
  end

  def password_blank?
    params[:user][:password].blank? && params[:user][:password_confirmation].blank?
  end
end

app/controllers/overtimes_controller.rb
# frozen_string_literal: true

class OvertimesController < BaseController
  include Selectable

  def index
    @q = current_user.overtimes.order(created_at: :desc).ransack(search_params)
    @current_collection = @q.result.page(params[:page])
    @current_collection = Kaminari.paginate_array(@current_collection.first(5)).page(params[:page]) if params[:q].blank?
  end

  def new
    @current_object = collection_scope.new
  end

  def create
    @current_object = collection_scope.new(resource_params)
    if @current_object.save
      action_success
    else
      render action: :new
    end
  end

  def update
    if current_object.canceled?
      action_fail t('warnings.not_cancellable'), :edit
    else
      current_object.assign_attributes(resource_params)
      if !current_object.changed?
        action_fail t('warnings.no_change'), :edit
      elsif current_object.revise!
        action_success
      else
        render action: :edit
      end
    end
  end

  def cancel
    if current_object.may_cancel?
      current_object.cancel!
      @actions << :cancel
      action_success
    elsif current_object.approved?
      action_fail t('warnings.already_happened'), :index
    else
      action_fail t('warnings.not_cancellable'), :index
    end
  end

  private

  def resource_params
    params.require(:overtime).permit(
      :start_time, :end_time, :description, :compensatory_type
    )
  end

  def collection_scope
    current_user.overtimes
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :status_eq, :end_time_lteq, :start_time_gteq, :compensatory_type_eq)
  end
end

app/helpers/backend/overtimes_helper.rb
# frozen_string_literal: true

module Backend
  module OvertimesHelper
    def overtime_submit_disabled?
      return unless current_object.pay?

      !current_object.may_approve? || current_object.overtime_pay&.hour.nil?
    end

    def render_append_hours_options
      if current_object.may_approve? && current_object.leave?
        link_to t('title.backend/overtimes.append_quota'), add_leave_time_backend_overtime_path, class: 'btn btn-warning'
      elsif current_object.may_approve? && current_object.pay?
        link_to t('title.backend/overtimes.append_overtime_pay'), add_compensatory_pay_backend_overtime_path, class: 'btn btn-warning'
      end
    end
  end
end

app/views/backend/overtimes/_form.html.haml
= simple_form_for current_object, url: backend_overtime_path(current_object), method: :put do |f|
  = f.input :comment
  = f.button :submit, t("title.backend/overtimes.approve"), disabled: overtime_submit_disabled?, name: "approve", class: "btn btn-primary"
  = f.button :submit, t("title.backend/overtimes.reject"), name: "reject", class: "btn btn-danger"
  = render_append_hours_options

app/views/backend/overtimes/add_compensatory_pay.html.haml
= simple_form_for @overtime_pay, url: create_compensatory_pay_backend_overtime_path, method: :post do |f|
	= f.input :user, input_html: {value: current_object.user.name}, disabled: true
	=	f.input :hour, input_html: {value: current_object.hours}
	=	f.input :remark, as: :text
	=	f.button :submit

app/views/backend/overtimes/add_leave_time.html.haml
= simple_form_for @leave_time, url: create_leave_time_backend_overtime_path, method: :post do |f|
	= f.input :user, input_html: {value: current_object.user.name}, disabled: true
	=	f.input :leave_type, collection: LeaveTime.enum_attributes_for_select(:leave_types)
	=	f.input :quota, input_html: {value: current_object.hours}
	=	f.input :effective_date,  as: :string, required: true, wrapper_html: { class: 'date-input' },
			input_html: { data: { input: 'datepicker', format: 'Y/m/d' }, value: Date.today }
	=	f.input :expiration_date, as: :string, required: true, wrapper_html: { class: 'date-input' },
			input_html: { data: { input: 'datepicker', format: 'Y/m/d' }, value: Date.today.end_of_year }
	=	f.input :remark, as: :text
	=	f.button :submit

app/views/backend/overtimes/index.html.haml
%h2= t("captions.backend/overtimes.index")

.panel.panel-default
  .panel-heading= t('panel_header.filter_conditions')
  .panel-body
    = simple_form_for @q, url: url_for(action: :index), method: :get do |f|
      = f.input :compensatory_type_eq, collection: Overtime.enum_attributes_for_select(:compensatory_types).map.with_index { |e, i| [e.first, i]},
        include_blank: t('.plz_select_compensatory_type'), required: false, wrapper_html: { class: 'col-xs-12' }
      = f.input :status_eq, collection: Overtime.enum_attributes_for_select(:statuses),
        include_blank: t('.plz_select_status'), required: false, wrapper_html: { class: 'col-md-6' }
      = f.input :user_id_eq, collection: @users, required: false,
        include_blank: t('.plz_select_user'), label_method: :name, value_method: :id,
        wrapper_html: { class: 'col-md-6' }
      = f.input :start_time_gteq, wrapper_html: { class: 'date-input col-md-6' },
        input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }, required: false
      = f.input :end_time_lteq, wrapper_html: { class: 'date-input col-md-6' },
        input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }, required: false
      
      .text-right
        = f.button :submit, class: 'btn-warning'

- if current_collection.any?
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr.info
        %th.text-right
          = sort_link(@q, :id, '#')
        %th.text-center
          = sort_link(@q, :compensatory_type)
        %th.text-center= t_attribute :user, Overtime
        %th.text-right
          = sort_link(@q, :start_time)
        %th.text-right
          = sort_link(@q, :end_time)
        %th.text-right
          = sort_link(@q, :hours)
        %th.text-center= t_attribute :status, Overtime
        %th.text-center= t("captions.tools")
    %tbody
      - current_collection.each do |ot|
        %tr
          %td.text-right= ot.id
          %td.text-center= Overtime.human_enum_value(:compensatory_type, ot.compensatory_type)
          %td.text-center= ot.user.name
          %td.text-right= l ot.start_time, format: :long
          %td.text-right= l ot.end_time, format: :long
          %td.text-right= ot.hours
          %td.text-center
            - colored_state_label(ot.status)
          %td.text-center
            - if ot.pending?
              = link_to t("title.backend/overtimes.verify"),
                verify_backend_overtime_path(ot),
                class: "btn btn-warning"
            - else
              = link_to t("title.backend/overtimes.show"),
                verify_backend_overtime_path(ot),
                class: "btn btn-primary"
- else
  = no_data_alert

.paginate
  = paginate current_collection

app/views/backend/overtimes/statistics.html.haml
%h2= t("captions.backend/overtimes.statistics")

.panel.panel-default
  .panel-heading= t('panel_header.filter_conditions')
  .panel-body
    = simple_form_for @q, url: url_for(action: :statistics), method: :get do |f|
      = f.input :year_eq, collection: (2016..Time.now.year).to_a.reverse,
        include_blank: t('.plz_select_year'), required: false, wrapper_html: { class: 'col-md-6' }
      = f.input :month_eq, collection: 1..12,
        include_blank: t('.plz_select_month'), required: false, wrapper_html: { class: 'col-md-6' }
      .text-right
        = f.button :submit, class: 'btn-warning'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %td.text-center= t('.application_id')
      %td.text-center= t('.user_name')
      %td.text-center= t('.start_time')
      %td.text-center= t('.end_time')
      %td.text-center= t('.hour')
  %tbody
    - @summary.each do |ot|
      %tr
        %td.text-center.name= ot.id
        %td.text-center= ot.user.name
        %td.text-center= l ot.start_time, format: :short
        %td.text-center= l ot.end_time, format: :short
        %td.text-center= ot.overtime_pay&.hour

app/views/backend/overtimes/verify.html.haml
.panel.panel-info
  .panel-heading
    %h4.panel-title= t("captions.backend/overtimes.verify")

  %table.table

    %tr
      %th= t_attribute :user, Overtime
      %td= current_object.user.name

    %tr
      %th= t_attribute(:start_time, current_object)
      %td= l current_object.start_time, format: :long

    %tr
      %th= t_attribute(:end_time, current_object)
      %td= l current_object.end_time, format: :long

    = tr_by_object :hours

    = tr_by_object :description

    %tr
      %th= t_attribute(:status, current_object)
      %td= Overtime.human_enum_value(:status, current_object.status)

    %tr
      %th= t_attribute(:sign_date, current_object)
      %td= current_object.sign_date ? l(current_object.sign_date, format: :long) : nil

    = tr_by_object :manager, :convert_user_object_to_name, :name

    %tr
      %th= t_attribute(:created_at, current_object)
      %td= l current_object.created_at, format: :long

    %tr
      %th= t_attribute(:updated_at, current_object)
      %td= l current_object.updated_at, format: :long

- if current_object.pending? or current_object.approved?
  = render "form", action: :verify