config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en/ do
    devise_for :users, skip: :omniauth_callbacks
    
    root "pages#index"

    if Rails.application.config.enable_sign_in_as
      get 'login_as', to: "sessions#login_as"
    end

    namespace :backend do
      resources :users

      resources :leave_applications, except: [:show, :destroy] do
        get :verify, on: :member
        get :statistics, on: :collection
      end

      resources :leave_times, except: [:edit, :update, :destroy] do
        post :append_quota, on: :collection
        get :batch_new, on: :collection
        post :batch_create, on: :collection
      end

      resources :overtimes, except: [:show, :destroy] do
        get :verify, :add_leave_time, :add_compensatory_pay, on: :member
        post :create_leave_time, :create_compensatory_pay, on: :member
        get :statistics, on: :collection
      end

      resources :bonus_leave_time_logs, only: [:index, :update]
    end

    resources :leave_applications, except: [:destroy] do
      member do
        put "cancel"
      end

      collection do
        get "/:status", to: "leave_applications#index",
                        constraints: { status: /pending|approved|rejected|canceled/ }
      end
    end

    resources :leave_times, only: [:index, :show]
    resources :remote, only: [:new, :create, :update, :edit]

    resources :overtimes, except: :destroy do
      member do
        put "cancel"
      end
    end

  end
end

app/views/shared/_flash.html.haml
- if flash.any?
  #flash
    - flash.each do |flash_type, message|
      .alert.alert-warning.alert-dismissible{ role: "alert" }
        %button.close{ type: "button", "data-dismiss": "alert", "aria-label": "Close" }
          %span{ "aria-hidden": "true" } &times;
        = message

app/views/shared/_footer.html.haml
#footer
  %p #{t("misc.company_name")} - #{Time.zone.today.year}

app/views/shared/_leave_application_dropdown.html.haml
%li.dropdown
  = dropdown_title t("nav.leave_applications")
  %ul.dropdown-menu
    %li= link_to t("title.leave_applications.new"), new_leave_application_path
    %li= link_to t("title.leave_applications.new_remote"), new_remote_path
    %li= link_to t("title.overtimes.new"), new_overtime_path
    %li= link_to t("title.leave_times.index"), leave_times_path
    %li= link_to t("title.leave_applications.index"), leave_applications_path
    %li= link_to t("title.overtimes.index"), overtimes_path

app/views/shared/_leave_applocation_dropdown_contractor.html.haml
%li.dropdown
  = dropdown_title t("nav.leave_applications")
  %ul.dropdown-menu
    %li= link_to t("title.leave_applications.new"), new_leave_application_path
    %li= link_to t("title.leave_applications.index"), leave_applications_path

app/views/shared/_leave_times_table.html.haml
%table.table
  %thead
    %tr
      - if show_leave_type
        %th.text-center= t('title.leave_times.type')
      - columns.each do |c|
        %th.text-right= t_attribute c, LeaveTime
      - if tools.present?
        %th.tools= t("captions.tools")

  %tbody
    - leave_times.each do |lt|
      %tr
        - if show_leave_type
          %th.text-center= t_value :leave_type, lt, :translate_text_value
        - columns.each do |c|
          %th.text-right= t_value c, lt
        - if tools.present?
          %td.tools= tools.call(lt)

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ "type": "button", "data-toggle": "collapse", "data-target": "#nav-collapse", "aria-expanded": "false" }
        %span.sr-only toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t("misc.app_title"), root_path, class: "navbar-brand"

    #nav-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if (can? :view, LeaveApplication) && !current_user.try(:contractor?)
          = render partial: 'shared/leave_application_dropdown'
        - if current_user.try(:contractor?)
          = render partial: 'shared/leave_applocation_dropdown_contractor'

        - if can? :manage, User
          %li.dropdown
            = dropdown_title t("nav.backend")
            %ul.dropdown-menu
              %li= link_to t("title.backend/users.index"), backend_users_path
              %li= link_to t("title.backend/users.new"), new_backend_user_path

        - if can? :manage, User
          %li.dropdown
            = dropdown_title t("nav.manage")
            %ul.dropdown-menu
              %li= link_to t("title.backend/leave_applications.new"), new_backend_leave_application_path
              %li= link_to t("title.backend/leave_applications.index"),
                backend_leave_applications_path(status: :pending)
              %li= link_to t("title.backend/overtimes.index"),
                backend_overtimes_path(q: {status_eq: :pending})
              %li= link_to t("captions.backend/leave_applications.statistics"),
                statistics_backend_leave_applications_path(year: specific_year, month: specific_month, role: "")
              %li= link_to t("captions.backend/overtimes.statistics"), statistics_backend_overtimes_path
              %li= link_to t("title.backend/leave_times.index"),
                backend_leave_times_path

        - if can? :manage, User
          %li.dropdown
            = dropdown_title t("nav.leave_times")
            %ul.dropdown-menu
              %li= link_to t("title.backend/leave_times.new"), new_backend_leave_time_path
              %li= link_to t("title.backend/leave_times.batch_append_quota"),batch_new_backend_leave_times_path

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            = dropdown_title current_user.login_name
            %ul.dropdown-menu
              %li= link_to t("title.devise/sessions.destroy"),
                destroy_user_session_path, method: :delete
        - else
          %li= link_to t("title.devise/sessions.new"), user_keycloak_omniauth_authorize_path, data: { turbolinks: false }

app/views/shared/_type_selector.html.haml
.row
  .col-md-3.col-sm-3.col-xs-6
    .form-group
      %label{:for=> name}= label
      = select_tag name,
        options_for_select(options, default), class: "form-control type-selector"

app/views/shared/_year_type_selector.html.haml
.row
  .col-md-6.col-sm-6.col-xs-6
    .form-group
      %label{:for=>"year"} 年度
      = select_tag :year,
        options_for_select( (2016 .. 2017), specific_year), class: "form-control"
  .col-md-6.col-sm-6.col-xs-6
    .form-group
      %label{:for=>"status"} 假別
      = select_tag :status,
        options_for_select(status_select_option, params[:status]), class: "form-control"