config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en/ do
    devise_for :users, skip: :omniauth_callbacks
    
    root "pages#index"

    if Rails.application.config.enable_sign_in_as
      get 'login_as', to: "sessions#login_as"
    end

    namespace :backend do
      resources :users

      resources :leave_applications, except: [:show, :destroy] do
        get :verify, on: :member
        get :statistics, on: :collection
      end

      resources :leave_times, except: [:edit, :update, :destroy] do
        post :append_quota, on: :collection
        get :batch_new, on: :collection
        post :batch_create, on: :collection
      end

      resources :overtimes, except: [:show, :destroy] do
        get :verify, :add_leave_time, :add_compensatory_pay, on: :member
        post :create_leave_time, :create_compensatory_pay, on: :member
        get :statistics, on: :collection
      end

      resources :bonus_leave_time_logs, only: [:index, :update]
    end

    resources :leave_applications, except: [:destroy] do
      member do
        put "cancel"
      end

      collection do
        get "/:status", to: "leave_applications#index",
                        constraints: { status: /pending|approved|rejected|canceled/ }
      end
    end

    resources :leave_times, only: [:index, :show]
    resources :remote, only: [:new, :create, :update, :edit]

    resources :overtimes, except: :destroy do
      member do
        put "cancel"
      end
    end

  end
end

app/models/leave_time.rb
# frozen_string_literal: true

class LeaveTime < ApplicationRecord
  delegate :seniority, :name, to: :user

  enum leave_type: Settings.leave_times.quota_types

  belongs_to :user
  has_many :leave_time_usages, dependent: :delete_all
  has_many :leave_applications, through: :leave_time_usages

  before_validation :set_default_values
  after_create :build_special_leave_time_usages

  validates :leave_type, :effective_date, :expiration_date, :quota, :usable_hours, :used_hours, :locked_hours, :user, presence: true
  validates :quota, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :usable_hours, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :used_hours, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :locked_hours, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :positive_range
  validate :balanced_hours

  scope :belong_to, ->(user) {
    where(user: user)
  }

  scope :personal, ->(user_id, leave_type, beginning, closing) {
    overlaps(beginning, closing).find_by(user_id: user_id, leave_type: leave_type)
  }

  scope :overlaps, ->(beginning, closing) {
    where(
      '(leave_times.effective_date, leave_times.expiration_date) OVERLAPS (timestamp :beginning, timestamp :closing)',
      beginning: beginning.beginning_of_day, closing: closing.end_of_day
    )
  }

  scope :effective, ->(date = Time.current) {
    overlaps(date.beginning_of_day, date.end_of_day)
  }

  ransacker :effective do |parent|
    Arel.sql("(select (leave_times.effective_date, leave_times.expiration_date) OVERLAPS (timestamp '#{Time.current.beginning_of_day}', timestamp '#{Time.current.end_of_day}'))")
  end

  def deduct(hours)
    self.used_hours += hours
    self.usable_hours = quota - used_hours
    save!
  end

  def cover?(time_format)
    date = time_format.to_date
    (self.effective_date..self.expiration_date).cover? date
  end

  def special_type?
    %w(marriage compassionate official maternity occpational_sick menstrual).include? self.leave_type
  end

  def lock_hours(hours)
    self.usable_hours -= hours
    self.locked_hours += hours
  end

  def lock_hours!(hours)
    self.lock_hours(hours)
    self.save!
  end

  def unlock_hours(hours)
    self.locked_hours -= hours
    self.usable_hours += hours
  end

  def unlock_hours!(hours)
    self.unlock_hours(hours)
    self.save!
  end

  def use_hours(hours)
    self.locked_hours -= hours
    self.used_hours += hours
  end

  def use_hours!(hours)
    self.use_hours(hours)
    self.save!
  end

  def direct_use_hours(hours)
    self.usable_hours -= hours
    self.used_hours += hours
  end

  def direct_use_hours!(hours)
    self.direct_use_hours(hours)
    self.save!
  end

  def unuse_hours(hours)
    self.used_hours -= hours
    self.usable_hours += hours
  end

  def unuse_hours!(hours)
    self.unuse_hours(hours)
    self.save!
  end

  def unuse_and_lock_hours(hours)
    self.used_hours -= hours
    self.locked_hours += hours
  end

  def unuse_and_lock_hours!(hours)
    self.unuse_and_lock_hours(hours)
    self.save!
  end

  private

  def set_default_values
    self.usable_hours ||= self.quota
    self.used_hours   ||= 0
    self.locked_hours ||= 0
  end

  def positive_range
    return if self.errors[:effective_date].any? || self.errors[:expiration_date].any?
    return if expiration_date >= effective_date

    errors.add(:effective_date, :range_should_be_positive)
  end

  def overlaps?
    LeaveTime.overlaps(effective_date, expiration_date)
      .where(user_id: user_id, leave_type: self.leave_type)
      .where.not(id: self.id).any?
  end

  def balanced_hours
    return if errors[:usable_hours].any? or errors[:used_hours].any? or errors[:locked_hours].any?

    errors.add(:quota, :unbalanced_hours) if quota != (usable_hours + used_hours + locked_hours)
  end

  def build_special_leave_time_usages
    return unless self.special_type?

    leave_applications = User.find(self.user_id).leave_applications.where(leave_type: self.leave_type).pending
    leave_applications.each do |la|
      if la.leave_time_usages.empty? and la.hours <= la.available_leave_times.pluck(:usable_hours).sum
        raise ActiveRecord::Rollback unless LeaveTimeUsageBuilder.new(la).build_leave_time_usages
      end
    end
  end
end

app/controllers/backend/base_controller.rb
# frozen_string_literal: true

class Backend::BaseController < ::BaseController
  before_action :authenticate_hr!

  def authenticate_hr!
    redirect_to root_path unless current_user.is_hr? || current_user.is_manager?
  end

  def authenticate_manager!
    redirect_to root_path unless current_user.is_manager?
  end
end

app/controllers/backend/leave_applications_controller.rb
# frozen_string_literal: true

class Backend::LeaveApplicationsController < Backend::BaseController
  include Selectable
  before_action :set_query_object

  def index
    @users = User.where.not(role: 'resigned')
  end

  def create
    @current_object = collection_scope.new(resource_params)
    if @current_object.save
      @current_object.approve!(current_user)
      action_success
    else
      render action: :new
    end
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def statistics
    usernames = params.dig(:usernames).to_s.split(',')
    if usernames.empty?
      @users = User.filter_by_role(%w[employee parttime])
    else
      @users = User.where(login_name: usernames)
    end
    @summary = LeaveTimeSummaryService.new(
      specific_year.to_i,
      specific_month.to_i,
      @users
    ).summary
  end

  private

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def collection_scope
    if params[:id]
      LeaveApplication
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    case action_name
    when 'create' then params.require(:leave_application).permit(:user_id, :leave_type, :start_time, :end_time, :description, :comment)
    when 'update' then params.require(:leave_application).permit(:comment)
    end
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :leave_type_eq, :user_id_eq, :status_eq, :end_date_gteq, :start_date_lteq)
    @search_params.present? ? @search_params : @search_params.merge(status_eq: :pending)
  end

  def set_query_object
    @q = LeaveApplication.ransack(search_params)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index, controller: controller_path, params: { status: :pending })
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/leave_times_controller.rb
# frozen_string_literal: true

class Backend::LeaveTimesController < Backend::BaseController
  before_action :set_query_object

  def index
  end

  def new
    @current_object = LeaveTime.new
  end

  def create
    @current_object = LeaveTime.new(resource_params)
    return render action: :new unless @current_object.save

    if request.env['HTTP_REFERER'].include?('leave_application_id')
      verify_id = request.env['HTTP_REFERER'].partition('=').last
      action_success(verify_backend_leave_application_path(verify_id))
    else
      action_success
    end
  end

  def append_quota
    @current_object = collection_scope.new(leave_time_params_by_leave_application)
    render :new
  end

  def batch_new
    @current_object = LeaveTime.new
  end

  def batch_create
    user_ids = params[:leave_time][:user_id]
    user_ids.each do |user_id|
      @current_object = LeaveTime.new(batch_leave_time_params.merge(user_id: user_id))
      return render action: :batch_new unless @current_object.save
    end
    action_success
  end

  private

  def leave_time_params_by_leave_application
    leave_application = LeaveApplication.find(params[:leave_application_id])
    leave_application.leave_time_params
  end

  def set_query_object
    @q = LeaveTime.ransack(search_params)
  end

  def collection_scope
    if params[:id]
      LeaveTime.preload(:user, leave_time_usages: :leave_application)
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    params.require(:leave_time).permit(
      :user_id, :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def batch_leave_time_params
    params.require(:leave_time).permit(
      :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :leave_type_eq, :effective_true, :user_id_eq)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index)
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/overtimes_controller.rb
# frozen_string_literal: true

class Backend::OvertimesController < Backend::BaseController
  before_action :set_query_object, except: :statistics

  def index
    @users = User.all
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def add_leave_time
    @leave_time = LeaveTime.new
  end

  def create_leave_time
    params[:leave_time][:user_id] = current_object.user.id
    @leave_time = LeaveTime.new(resource_params)
    if @leave_time.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_leave_time
    end
  end

  def add_compensatory_pay
    @overtime_pay = OvertimePay.new
  end

  def create_compensatory_pay
    params[:overtime_pay][:user_id] = current_object.user.id
    params[:overtime_pay][:overtime_id] = params[:id]
    @overtime_pay = OvertimePay.new(resource_params)
    if @overtime_pay.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_overtime_pay
    end
  end

  def statistics
    search_params = params.fetch(:q, {})&.permit(:year_eq, :month_eq)
    @q = Overtime.where(compensatory_type: 'pay', status: :approved).ransack(search_params)
    @summary = @q.result
  end

  private

  def resource_params
    case action_name
    when 'create' then params.require(:overtime).permit(:user_id, :hours, :start_time, :end_time, :description)
    when 'update' then params.require(:overtime).permit(:comment)
    when 'create_leave_time' then params.require(:leave_time).permit(:user_id, :overtime_id, :leave_type, :quota, :effective_date, :expiration_date, :remark)
    when 'create_compensatory_pay' then params.require(:overtime_pay).permit(:user_id, :overtime_id, :hour, :remark)
    end
  end

  def set_query_object
    @q = Overtime.ransack(search_params)
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :status_eq, :end_time_lteq, :start_time_gteq, :compensatory_type_eq)
  end

  def collection_scope
    @q.result.preload(:user)
  end

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

class Backend::UsersController < Backend::BaseController
  before_action :set_query_object
  before_action :set_minimum_password_length, only: %i(new edit)

  def show
    @leave_times = current_object.leave_times
  end

  def update
    if password_blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    super
  end

  def new
    @current_object = User.new
  end

  def edit
  end

  private

  def set_query_object
    @q = User.ransack(search_params)
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :id_eq, :role_eq, :login_name_cont_any)
  end

  def collection_scope
    if params[:id]
      User
    else
      @q.result.order(id: :desc).page(params[:page])
    end
  end

  def resource_params
    params.require(:user).permit(
      :id, :name, :email, :login_name, :role,
      :password, :password_confirmation,
      :join_date, :leave_date,
      :assign_leave_time, :assign_date
    )
  end

  def set_minimum_password_length
    @minimum_password_length = 6
  end

  def password_blank?
    params[:user][:password].blank? && params[:user][:password_confirmation].blank?
  end
end

app/controllers/leave_times_controller.rb
# frozen_string_literal: true

class LeaveTimesController < BaseController
  STARTING_YEAR = Settings.misc.starting_year.to_i
  SHOWINGS = %i(all effective).freeze
  DEFAULT_SHOWING = 'effective'
  before_action :set_query_object

  helper_method :showing

  def index; end

  def showing
    @showing ||= params[:showing] || DEFAULT_SHOWING
  end

  private

  def collection_scope
    if params[:id]
      current_user.leave_times.preload(:user, leave_time_usages: :leave_application)
    else
      @q.result.preload(:user)
    end
  end

  def set_query_object
    @q = current_user.leave_times.ransack(search_params)
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(:s, :leave_type_eq, :effective_true)
    @search_params.present? ? @search_params : @search_params.merge(effective_true: true)
  end
end

app/helpers/backend/overtimes_helper.rb
# frozen_string_literal: true

module Backend
  module OvertimesHelper
    def overtime_submit_disabled?
      return unless current_object.pay?

      !current_object.may_approve? || current_object.overtime_pay&.hour.nil?
    end

    def render_append_hours_options
      if current_object.may_approve? && current_object.leave?
        link_to t('title.backend/overtimes.append_quota'), add_leave_time_backend_overtime_path, class: 'btn btn-warning'
      elsif current_object.may_approve? && current_object.pay?
        link_to t('title.backend/overtimes.append_overtime_pay'), add_compensatory_pay_backend_overtime_path, class: 'btn btn-warning'
      end
    end
  end
end

app/views/backend/leave_times/_form.html.haml
%h2= t("captions.backend/leave_times.#{action_name}")

= simple_form_for [:backend, current_object] do |f|
  = f.association :user, required: true, collection: User.where.not(role: 'resigned')
  = f.input :leave_type, required: true, collection: LeaveTime.enum_attributes_for_select(:leave_types)
  = f.input :quota
  = f.input :effective_date,  as: :string, required: true, wrapper_html: { class: 'date-input' },
    input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }
  = f.input :expiration_date, as: :string, required: true, wrapper_html: { class: 'date-input' },
    input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }
  = f.input :remark, as: :text
  - unless current_object.new_record?
    = f.input :usable_hours
    = f.input :used_hours
    = link_to t("title.backend/leave_times.delete"), backend_leave_time_path(current_object), method: :delete, class: "btn btn-sm btn-danger", data: {confirm: "Are you sure?"}
  = f.button :submit

app/views/backend/leave_times/batch_new.html.haml
%h2= t("captions.backend/leave_times.#{action_name}")

= simple_form_for current_object, url: batch_create_backend_leave_times_path do |f|
	= f.association :user, required: true, collection: User.where.not(role: 'resigned'),as: :check_boxes, include_hidden: false, item_wrapper_class: "checkbox-inline", label: false
	= f.input :leave_type, required: true, collection: LeaveTime.enum_attributes_for_select(:leave_types)
	= f.input :quota
	= f.input :effective_date,  as: :string, required: true, wrapper_html: { class: 'date-input' },
		input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }
	= f.input :expiration_date, as: :string, required: true, wrapper_html: { class: 'date-input' },
		input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }
	= f.input :remark, as: :text
	- unless current_object.new_record?
		= f.input :usable_hours
		= f.input :used_hours
		= link_to t("title.backend/leave_times.delete"), backend_leave_time_path(current_object), method: :delete, class: "btn btn-sm btn-danger", data: {confirm: "Are you sure?"}
	= f.button :submit

app/views/backend/leave_times/edit.html.haml
= render "form"

app/views/backend/leave_times/index.html.haml
%h2
  = t("captions.backend/leave_times.index")
  = link_to t("title.backend/leave_times.new"), new_backend_leave_time_path, class: 'btn btn-primary'

.panel.panel-default
  .panel-heading= t('panel_header.filter_conditions')
  .panel-body
    = simple_form_for @q, url: url_for(action: :index), method: :get do |f|
      = f.hidden_field :s, value: params.dig(:q, :s)
      = f.input :leave_type_eq, collection: LeaveTime.enum_attributes_for_select(:leave_types),
        include_blank: t('.plz_select_leave_type'), required: false,
        wrapper_html: { class: 'col-md-6' }
      = f.input :user_id_eq, collection: options_for_user_select, label_method: :first, value_method: :second, required: false,
        include_blank: t('.plz_select_user'), wrapper_html: { class: 'col-md-6' }
      = f.input :effective_true, collection: [[I18n.t('activerecord.attributes.leave_time.state.effective'), true], [I18n.t('activerecord.attributes.leave_time.state.expired'), false]],
        include_blank: t('.plz_select_effectiveness_state'), required: false,
        wrapper_html: { class: 'col-md-6' }

      .text-right
        = f.button :submit, class: 'btn-warning'

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr.info
      %th.text-right
        = sort_link(@q, :id, '#')
      %th.text-center= t_attribute :user, LeaveTime
      %th.text-center= t_attribute :leave_type, LeaveTime
      %th.text-right
        = sort_link(@q, :quota)
      %th.text-right
        = sort_link(@q, :locked_hours)
      %th.text-right
        = sort_link(@q, :used_hours)
      %th.text-right
        = sort_link(@q, :usable_hours)
      %th.text-right
        = sort_link(@q, :effective_date)
      %th.text-right
        = sort_link(@q, :expiration_date)
  %tbody
    - current_collection.each do |quota|
      %tr
        %td.text-right
          = link_to quota.id, backend_leave_time_path(quota.id)
        %td.text-center= quota.user.name
        %td.text-center= LeaveTime.human_enum_value(:leave_type, quota.leave_type)
        %td.text-right= hours_to_humanize quota.quota
        %td.text-right= hours_to_humanize quota.locked_hours
        %td.text-right= hours_to_humanize quota.used_hours
        %td.text-right= hours_to_humanize quota.usable_hours
        %td.text-right= l quota.effective_date, format: :detailed
        %td.text-right= l quota.expiration_date, format: :detailed
  %tfoot
    %tr
      %th.text-right{colspan: 3} Sum
      %td.active.text-right= hours_to_humanize current_collection.to_a.sum(&:quota)
      %td.active.text-right= hours_to_humanize current_collection.to_a.sum(&:locked_hours)
      %td.active.text-right= hours_to_humanize current_collection.to_a.sum(&:used_hours)
      %td.active.text-right= hours_to_humanize current_collection.to_a.sum(&:usable_hours)

.text-center
  = paginate current_collection

app/views/backend/leave_times/new.html.haml
= render "form"

app/views/backend/leave_times/show.html.haml
%h2= t '.title', id: current_object.id, user_name: current_object.user.name, leave_type: LeaveTime.human_enum_value(:leave_type, current_object.leave_type)

.panel.panel-primary
  .panel-heading
    %h3.panel-title= t('.quota_info')
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr.active
        %th.text-right #
        %th= t_attribute :leave_type, LeaveTime
        %th= t_attribute :user, LeaveTime
        %th.text-right= t_attribute :quota, LeaveTime
        %th.text-right= t_attribute :locked_hours, LeaveTime
        %th.text-right= t_attribute :used_hours, LeaveTime
        %th.text-right= t_attribute :usable_hours, LeaveTime
        %th.text-right= t_attribute :effective_date, LeaveTime
        %th.text-right= t_attribute :expiration_date, LeaveTime
    %tbody
      %tr
        %td.text-right= current_object.id
        %td= LeaveTime.human_enum_value(:leave_type, current_object.leave_type)
        %td= current_object.user.name
        %td.text-right= hours_to_humanize current_object.quota
        %td.text-right= hours_to_humanize current_object.locked_hours
        %td.text-right= hours_to_humanize current_object.used_hours
        %td.text-right= hours_to_humanize current_object.usable_hours
        %td.text-right= l current_object.effective_date, format: :detailed
        %td.text-right= l current_object.expiration_date, format: :detailed
      %tr
        %th.text-right.active{colspan: 2}= t_attribute :remark, LeaveTime
        %td{colspan: 7}= current_object.remark

.panel.panel-warning
  .panel-heading
    %h3.panel-title= t('.quota_usage_info')
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr.active
        %th.text-right #
        %th.text-center= t_attribute :leave_type, LeaveApplication
        %th.text-right= t('.used_locked_hours')
        %th.text-right= t('.used_hours')
        %th.text-right= t('.application_total_hours')
        %th.text-center= t_attribute :status, LeaveApplication
        %th.text-right= t_attribute :start_time, LeaveApplication
        %th.text-right= t_attribute :end_time, LeaveApplication
    %tbody
      - current_object.leave_time_usages.group_by(&:leave_application).each do |usage|
        %tr
          %td.text-right
            = link_to usage[0].id, verify_backend_leave_application_path(usage[0])
          %td.text-center= LeaveApplication.human_enum_value(:leave_type, usage[0].leave_type)
          %td.text-right= usage[0].pending? ? hours_to_humanize(usage[1].sum(&:used_hours)) : '-'
          %td.text-right= usage[0].approved? ? hours_to_humanize(usage[1].sum(&:used_hours)) : '-'
          %td.text-right= hours_to_humanize usage[0].hours
          %td.text-center
            - colored_state_label(usage[0].status)
          %td.text-right= l usage[0].start_time, format: :long
          %td.text-right= l usage[0].end_time,   format: :long

      %tr
        %th.active.text-right{colspan: 2}= t('.sum')
        %td.text-right= hours_to_humanize current_object.leave_time_usages.select { |u| u.leave_application.pending? }.sum(&:used_hours)
        %td.text-right= hours_to_humanize current_object.leave_time_usages.select { |u| u.leave_application.approved? }.sum(&:used_hours)
        %td{colspan: 5}