config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    delete "user/sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  scope "(:locale)", locale: /en/ do
    devise_for :users, skip: :omniauth_callbacks
    
    root "pages#index"

    if Rails.application.config.enable_sign_in_as
      get 'login_as', to: "sessions#login_as"
    end

    namespace :backend do
      resources :users

      resources :leave_applications, except: [:show, :destroy] do
        get :verify, on: :member
        get :statistics, on: :collection
      end

      resources :leave_times, except: [:edit, :update, :destroy] do
        post :append_quota, on: :collection
        get :batch_new, on: :collection
        post :batch_create, on: :collection
      end

      resources :overtimes, except: [:show, :destroy] do
        get :verify, :add_leave_time, :add_compensatory_pay, on: :member
        post :create_leave_time, :create_compensatory_pay, on: :member
        get :statistics, on: :collection
      end

      resources :bonus_leave_time_logs, only: [:index, :update]
    end

    resources :leave_applications, except: [:destroy] do
      member do
        put "cancel"
      end

      collection do
        get "/:status", to: "leave_applications#index",
                        constraints: { status: /pending|approved|rejected|canceled/ }
      end
    end

    resources :leave_times, only: [:index, :show]
    resources :remote, only: [:new, :create, :update, :edit]

    resources :overtimes, except: :destroy do
      member do
        put "cancel"
      end
    end

  end
end

app/controllers/backend/base_controller.rb
# frozen_string_literal: true

class Backend::BaseController < ::BaseController
  before_action :authenticate_hr!

  def authenticate_hr!
    redirect_to root_path unless current_user.is_hr? || current_user.is_manager?
  end

  def authenticate_manager!
    redirect_to root_path unless current_user.is_manager?
  end
end

app/controllers/backend/leave_applications_controller.rb
# frozen_string_literal: true

class Backend::LeaveApplicationsController < Backend::BaseController
  include Selectable
  before_action :set_query_object

  def index
    @users = User.where.not(role: 'resigned')
  end

  def create
    @current_object = collection_scope.new(resource_params)
    if @current_object.save
      @current_object.approve!(current_user)
      action_success
    else
      render action: :new
    end
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def statistics
    usernames = params.dig(:usernames).to_s.split(',')
    if usernames.empty?
      @users = User.filter_by_role(%w[employee parttime])
    else
      @users = User.where(login_name: usernames)
    end
    @summary = LeaveTimeSummaryService.new(
      specific_year.to_i,
      specific_month.to_i,
      @users
    ).summary
  end

  private

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def collection_scope
    if params[:id]
      LeaveApplication
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    case action_name
    when 'create' then params.require(:leave_application).permit(:user_id, :leave_type, :start_time, :end_time, :description, :comment)
    when 'update' then params.require(:leave_application).permit(:comment)
    end
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :leave_type_eq, :user_id_eq, :status_eq, :end_date_gteq, :start_date_lteq)
    @search_params.present? ? @search_params : @search_params.merge(status_eq: :pending)
  end

  def set_query_object
    @q = LeaveApplication.ransack(search_params)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index, controller: controller_path, params: { status: :pending })
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/leave_times_controller.rb
# frozen_string_literal: true

class Backend::LeaveTimesController < Backend::BaseController
  before_action :set_query_object

  def index
  end

  def new
    @current_object = LeaveTime.new
  end

  def create
    @current_object = LeaveTime.new(resource_params)
    return render action: :new unless @current_object.save

    if request.env['HTTP_REFERER'].include?('leave_application_id')
      verify_id = request.env['HTTP_REFERER'].partition('=').last
      action_success(verify_backend_leave_application_path(verify_id))
    else
      action_success
    end
  end

  def append_quota
    @current_object = collection_scope.new(leave_time_params_by_leave_application)
    render :new
  end

  def batch_new
    @current_object = LeaveTime.new
  end

  def batch_create
    user_ids = params[:leave_time][:user_id]
    user_ids.each do |user_id|
      @current_object = LeaveTime.new(batch_leave_time_params.merge(user_id: user_id))
      return render action: :batch_new unless @current_object.save
    end
    action_success
  end

  private

  def leave_time_params_by_leave_application
    leave_application = LeaveApplication.find(params[:leave_application_id])
    leave_application.leave_time_params
  end

  def set_query_object
    @q = LeaveTime.ransack(search_params)
  end

  def collection_scope
    if params[:id]
      LeaveTime.preload(:user, leave_time_usages: :leave_application)
    else
      @q.result.preload(:user)
    end
  end

  def resource_params
    params.require(:leave_time).permit(
      :user_id, :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def batch_leave_time_params
    params.require(:leave_time).permit(
      :leave_type, :quota, :effective_date, :expiration_date, :usable_hours, :used_hours, :remark
    )
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :leave_type_eq, :effective_true, :user_id_eq)
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index)
    else
      request.env['HTTP_REFERER']
    end
  end
end

app/controllers/backend/overtimes_controller.rb
# frozen_string_literal: true

class Backend::OvertimesController < Backend::BaseController
  before_action :set_query_object, except: :statistics

  def index
    @users = User.all
  end

  def verify; end

  def update
    if current_object.update(resource_params)
      params[:approve] ? approve : reject
    else
      respond_to do |f|
        f.html { render action: :verify }
        f.json
      end
    end
  end

  def add_leave_time
    @leave_time = LeaveTime.new
  end

  def create_leave_time
    params[:leave_time][:user_id] = current_object.user.id
    @leave_time = LeaveTime.new(resource_params)
    if @leave_time.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_leave_time
    end
  end

  def add_compensatory_pay
    @overtime_pay = OvertimePay.new
  end

  def create_compensatory_pay
    params[:overtime_pay][:user_id] = current_object.user.id
    params[:overtime_pay][:overtime_id] = params[:id]
    @overtime_pay = OvertimePay.new(resource_params)
    if @overtime_pay.save(resource_params)
      action_success(verify_backend_overtime_path(current_object))
    else
      render :add_overtime_pay
    end
  end

  def statistics
    search_params = params.fetch(:q, {})&.permit(:year_eq, :month_eq)
    @q = Overtime.where(compensatory_type: 'pay', status: :approved).ransack(search_params)
    @summary = @q.result
  end

  private

  def resource_params
    case action_name
    when 'create' then params.require(:overtime).permit(:user_id, :hours, :start_time, :end_time, :description)
    when 'update' then params.require(:overtime).permit(:comment)
    when 'create_leave_time' then params.require(:leave_time).permit(:user_id, :overtime_id, :leave_type, :quota, :effective_date, :expiration_date, :remark)
    when 'create_compensatory_pay' then params.require(:overtime_pay).permit(:user_id, :overtime_id, :hour, :remark)
    end
  end

  def set_query_object
    @q = Overtime.ransack(search_params)
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :status_eq, :end_time_lteq, :start_time_gteq, :compensatory_type_eq)
  end

  def collection_scope
    @q.result.preload(:user)
  end

  def approve
    if current_object.pending?
      current_object.approve!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end

  def reject
    if current_object.pending? or current_object.approved?
      current_object.reject!(current_user)
      action_success
    else
      action_fail t('warnings.not_verifiable'), :verify
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

class Backend::UsersController < Backend::BaseController
  before_action :set_query_object
  before_action :set_minimum_password_length, only: %i(new edit)

  def show
    @leave_times = current_object.leave_times
  end

  def update
    if password_blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    super
  end

  def new
    @current_object = User.new
  end

  def edit
  end

  private

  def set_query_object
    @q = User.ransack(search_params)
  end

  def search_params
    params.fetch(:q, {})&.permit(:s, :id_eq, :role_eq, :login_name_cont_any)
  end

  def collection_scope
    if params[:id]
      User
    else
      @q.result.order(id: :desc).page(params[:page])
    end
  end

  def resource_params
    params.require(:user).permit(
      :id, :name, :email, :login_name, :role,
      :password, :password_confirmation,
      :join_date, :leave_date,
      :assign_leave_time, :assign_date
    )
  end

  def set_minimum_password_length
    @minimum_password_length = 6
  end

  def password_blank?
    params[:user][:password].blank? && params[:user][:password_confirmation].blank?
  end
end

app/controllers/leave_applications_controller.rb
# frozen_string_literal: true

class LeaveApplicationsController < BaseController
  include Selectable
  before_action :set_query_object
  after_action :auto_approve_for_contractor, only: [:create, :update], if: :contractor?

  def index
    @current_collection = collection_scope.page(params[:page])
    @current_collection = Kaminari.paginate_array(@current_collection.first(5)).page(params[:page]) unless query?
    @current_collection = @current_collection.with_status(params[:status]) if status_selected?
  end

  def create
    @current_object = collection_scope.new(resource_params)
    if @current_object.save
      action_success
    else
      render action: :new
    end
  end

  def update
    if current_object.canceled?
      action_fail t('warnings.not_cancellable'), :edit
    else
      current_object.assign_attributes(resource_params)
      if !current_object.changed?
        action_fail t('warnings.no_change'), :edit
      elsif current_object.revise!
        action_success
      else
        render action: :edit
      end
    end
  end

  def cancel
    if current_object.may_cancel?
      current_object.cancel!
      @actions << :cancel
      action_success
    elsif current_object.approved?
      action_fail t('warnings.already_happened'), :index
    else
      action_fail t('warnings.not_cancellable'), :index
    end
  end

  private

  def collection_scope
    if params[:id]
      current_user.leave_applications
    else
      @q.result.where(user_id: current_user.id).order(id: :desc).page(params[:page])
    end
  end

  def query?
    !params[:q].nil?
  end

  def search_params
    @search_params = params.fetch(:q, {})&.permit(
      :s, :leave_type_eq, :status_eq, :end_date_gteq, :start_date_lteq)
  end

  def set_query_object
    @q = current_user.leave_applications.ransack(search_params)
  end

  def resource_params
    params.require(:leave_application).permit(
      :leave_type, :start_time, :end_time, :description, :attachment
    )
  end

  def url_after(action)
    if @actions.include?(action)
      url_for(action: :index, controller: controller_path)
    else
      request.env['HTTP_REFERER']
    end
  end

  def auto_approve_for_contractor
    current_object.approve!(current_user)
  end

  def contractor?
    current_user.contractor?
  end
end

app/helpers/backend/overtimes_helper.rb
# frozen_string_literal: true

module Backend
  module OvertimesHelper
    def overtime_submit_disabled?
      return unless current_object.pay?

      !current_object.may_approve? || current_object.overtime_pay&.hour.nil?
    end

    def render_append_hours_options
      if current_object.may_approve? && current_object.leave?
        link_to t('title.backend/overtimes.append_quota'), add_leave_time_backend_overtime_path, class: 'btn btn-warning'
      elsif current_object.may_approve? && current_object.pay?
        link_to t('title.backend/overtimes.append_overtime_pay'), add_compensatory_pay_backend_overtime_path, class: 'btn btn-warning'
      end
    end
  end
end

app/helpers/leave_applications_helper.rb
# frozen_string_literal: true

module LeaveApplicationsHelper
  def time_object_by_hour_min(hour, min)
    Time.zone.now.change(hour: hour, min: min)
  end

  def date_time_picker_hash(key, time_object)
    { as: :date_time_picker, time: key.to_s, input_html: { value: time_object }, require: true }
  end

  def colored_state_label(status)
    humanize_status = LeaveApplication.human_enum_value(:statuses, status)
    case status.to_sym
    when :pending
      haml_tag :span, humanize_status, class: 'label label-primary'
    when :canceled
      haml_tag :span, humanize_status, class: 'label label-default'
    when :approved
      haml_tag :span, humanize_status, class: 'label label-success'
    when :rejected
      haml_tag :span, humanize_status, class: 'label label-danger'
    else
      haml_tag :span, humanize_status, class: 'label label-danger'
    end
  end

  def need_deduct_salary?(leave_type, leave_time)
    return if leave_time.zero?

    %w(personal halfpaid_sick).include? leave_type
  end

  def summary_from(summary, user_id)
    leave_types = Settings.leave_times.quota_types.keys
    summary[user_id] || Hash[leave_types.collect { |type| [type, 0] }]
  end

  def leave_type_dropdown_menu(action_name, user)
    if user.role == 'contractor'
      LeaveApplication.enum_attributes_for_select(:leave_types, [:remote, :sick, :maternity, :marriage, :compassionate, :official, :occpational_sick, :menstrual])
    else
      LeaveApplication.enum_attributes_for_select(:leave_types)
    end
  end

  def link_to_attachment(attachment)
    link_to t('.exam_attachment'), current_object.attachment.url, target: :_blank, rel: 'noopener' if attachment
  end
end

app/views/backend/leave_applications/_form.html.haml
- if action == :verify
  = simple_form_for current_object, url: backend_leave_application_path(current_object), method: :put do |f|
    = f.input :comment
    = f.button :submit, t("title.backend/leave_applications.approve"), disabled: !current_object.may_approve?, name: "approve", class: "btn btn-primary"
    = f.button :submit, t("title.backend/leave_applications.reject"), name: "reject", class: "btn btn-danger"
    - if current_object.special_type? and not current_object.may_approve?
      = link_to t("title.backend/leave_applications.append_quota"), append_quota_backend_leave_times_path(leave_application_id: current_object), method: :post, class: 'btn btn-warning'

- elsif action == :create
  %h2= t("captions.backend/leave_applications.#{action_name}")
  %p= t("captions.backend/leave_applications.#{action_name}/hint")
  = simple_form_for current_object, url: url_for(action: action), method: :post do |f|
    = f.association :user, collection: User.where.not(role: 'resigned'), label_method: :name, value_method: :id, required: true
    = f.error :base, error: sanitize(f.object.errors[:base].join('<br />'), tags: %w(a br), attributes: %w(href target))
    = f.input :leave_type, required: true, collection: LeaveApplication.enum_attributes_for_select(:leave_types)
    = f.input :start_time, as: :string, input_html: { data: { input: 'datetimepicker', format: 'Y/m/d H:i' } }
    = f.input :end_time,   as: :string, input_html: { data: { input: 'datetimepicker', format: 'Y/m/d H:i' } }
    = f.error :hours, error: sanitize(f.object.errors[:hours].join('<br />'), tags: %w(br))
    = f.input :description, required: true
    = f.input :comment
    = f.button :submit, class: "submit"

app/views/backend/leave_applications/index.html.haml
%h2= t("captions.backend/leave_applications.index")

.panel.panel-default
  .panel-heading= t('panel_header.filter_conditions')
  .panel-body
    = simple_form_for @q, url: url_for(action: :index), method: :get do |f|
      = f.hidden_field :s, value: params.dig(:q, :s)
      = f.input :status_eq, collection: LeaveApplication.enum_attributes_for_select(:statuses),
        include_blank: t('.plz_select_status'), required: false, wrapper_html: { class: 'col-md-4' }
      = f.input :leave_type_eq, collection: LeaveApplication.enum_attributes_for_select(:leave_types),
        include_blank: t('.plz_select_leave_type'), required: false, wrapper_html: { class: 'col-md-4' }
      = f.input :user_id_eq, collection: @users, required: false,
        include_blank: t('.plz_select_user'), label_method: :name, value_method: :id,
        wrapper_html: { class: 'col-md-4' }
      = f.input :end_date_gteq, wrapper_html: { class: 'date-input col-md-6' },
        input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }, required: false
      = f.input :start_date_lteq, wrapper_html: { class: 'date-input col-md-6' },
        input_html: { data: { input: 'datepicker', format: 'Y/m/d' } }, required: false

      .text-right
        = f.button :submit, class: 'btn-warning'

- if current_collection.any?
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr.info
        %th.text-right
          = sort_link(@q, :id, '#')
        %th.text-center= t_attribute :user, LeaveApplication
        %th.text-center= t_attribute :leave_type, LeaveApplication
        %th.text-right
          = sort_link(@q, :start_time)
        %th.text-right
          = sort_link(@q, :end_time)
        %th.text-right
          = sort_link(@q, :hours)
        %th.text-center= t_attribute :status, LeaveApplication
        %th.text-center= t("captions.tools")
    %tbody
      - current_collection.each do |leave|
        %tr
          %td.text-right= leave.id
          %td.text-center= t_value :user, leave, :convert_user_object_to_name, :name
          %td.text-center= LeaveApplication.human_enum_value(:leave_type, leave.leave_type)
          %td.text-right= l leave.start_time, format: :long
          %td.text-right= l leave.end_time, format: :long
          %td.text-right= hours_to_humanize(leave.hours)
          %td.text-center
            - colored_state_label(leave.status)
          %td.text-center
            - if leave.pending?
              = link_to t("title.backend/leave_applications.verify"),
                verify_backend_leave_application_path(leave),
                class: "btn btn-warning"
            - else
              = link_to t("title.backend/leave_applications.show"),
                verify_backend_leave_application_path(leave),
                class: "btn btn-primary"
- else
  = no_data_alert

.paginate
  = paginate current_collection

app/views/backend/leave_applications/new.html.haml
= render "form", action: :create

app/views/backend/leave_applications/statistics.html.haml
%h2= t("captions.backend/leave_applications.statistics", year: specific_year, month: specific_month, role: params[:role])


.panel.panel-default
  .panel-body
    .year-mon-selector
      .row
        .col-md-4.col-sm-4.col-xs-12
          .form-group
            %label{:for=>"year"} Year
            = select_tag "year",
              options_for_select(2016 .. Time.now.year, specific_year),
              class: "form-control"

        .col-md-4.col-sm-4.col-xs-12
          .form-group
            %label{:for=>"month"} Month
            = select_tag "month", options_for_select(1..12, specific_month),
              class: "form-control"

        .col-md-4.col-sm-4.col-xs-12
          .form-group
            %label{:for=>"role"} Role
            = select_tag "role", options_for_select(User.enum_attributes_for_select(:roles), params[:role]),
              include_blank:true, class: "form-control"


%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr.info
      %th.text-center.name=  t_attribute(:name, User)
      - Settings.leave_times.quota_types.keys.each do |leave_type|
        %th.text-right= t("activerecord.attributes.leave_time.leave_types.#{leave_type}")
      %th.text-right 總計
  %tbody
    - @users.each do |user|
      %tr
        %td.text-center.name= user.name
        - summary_from(@summary, user.id).each do |key, value|
          %td.text-right{ class: ('highlight' if need_deduct_salary?(key, value)) }= hours_for_total value
        %td.text-right= hours_to_humanize summary_from(@summary, user.id).values.sum

app/views/backend/leave_applications/verify.html.haml
.panel.panel-info
  .panel-heading
    %h4.panel-title= t("captions.backend/leave_applications.verify")

  %table.table

    %tr
      %th= t_attribute :user, LeaveApplication
      %td= current_object.user_name

    %tr
      %th= t_attribute(:leave_type, current_object)
      %td= LeaveTime.human_enum_value(:leave_types, current_object.leave_type)

    %tr
      %th= t_attribute(:start_time, current_object)
      %td= l current_object.start_time, format: :long

    %tr
      %th= t_attribute(:end_time, current_object)
      %td= l current_object.end_time, format: :long

    = tr_by_object :hours

    %tr
      %th= t_attribute(:leave_time_usage_builder, current_object)
      %td
        - current_object.leave_hours_by_dates.each do |date|
          %li #{ l date.date, format: :detailed }：#{ date.hours } 小時
    = tr_by_object :description

    %tr
      %th= t_attribute(:status, current_object)
      %td= LeaveApplication.human_enum_value(:status, current_object.status)

    %tr
      %th= t_attribute(:sign_date, current_object)
      %td= current_object.sign_date ? l(current_object.sign_date, format: :long) : nil

    = tr_by_object :manager, :convert_user_object_to_name, :name

    %tr
      %th= t_attribute(:created_at, current_object)
      %td= l current_object.created_at, format: :long

    %tr
      %th= t_attribute(:updated_at, current_object)
      %td= l current_object.updated_at, format: :long

    %tr
      %th= t_attribute(:attachment, current_object)
      %td= link_to_attachment(current_object.attachment.url)

.panel.panel-info
  .panel-heading
    %h4.panel-title= t_attribute(:leave_time_usages, current_object)
  %table.table
    %thead
      %tr
        %th.text-right #
        %th.text-center 假別
        %th.text-right 日期
        %th.text-right 使用時數
        %th.text-right 餘額
        %th.text-right 生效日期
        %th.text-right 失效日期
    %tbody
      - current_object.leave_time_usages.each do |usage|
        %tr
          %td.text-right= link_to usage.leave_time_id, backend_leave_time_path(usage.leave_time_id)
          %td.text-center= LeaveTime.human_enum_value(:leave_type, usage.leave_time.leave_type)
          %td.text-right= usage.date

          %td.text-right= hours_to_humanize usage.used_hours
          %td.text-right= hours_to_humanize usage.leave_time.usable_hours
          %td.text-right= l usage.leave_time.effective_date, format: :detailed
          %td.text-right= l usage.leave_time.expiration_date, format: :detailed

- if current_object.pending? or current_object.approved?
  = render "form", action: :verify